### ISSUE TITLE
SpockApprovals.verify() doesn't work

### ISSUE THREAD

**Issue by dpost** [rzabini/ApprovalTests.Spock#1]
The verifyAll method works, but verify throws an exception:

```
Caused by: java.lang.RuntimeException: Could not find Junit/TestNg TestCase you are running
	at org.approvaltests.namer.AttributeStackSelector.selectElement(AttributeStackSelector.java:59)
	at com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:265)
	at com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:258)
	at org.approvaltests.namer.StackTraceNamer.<init>(StackTraceNamer.java:13)
	at org.approvaltests.Approvals$1.load(Approvals.java:50)
	at org.approvaltests.Approvals$1.load(Approvals.java:47)
	at org.approvaltests.Approvals.createApprovalNamer(Approvals.java:168)
	at org.approvaltests.Approvals.verify(Approvals.java:124)
	at org.approvaltests.Approvals.verify(Approvals.java:222)
```

It seems that verifyAll uses the overridden SpockStackTraceNamer but verify uses the default StackTraceNamer for some reason

**Comment by dpost** [comment]
You can replicate this by changing LoggingSpecification in your sample code to use verify instead of verifyAll. 

As far as I can tell this is a nuance of the Java classloader that is causing the static block to be executed before verifyAll but not verify. I am able to work around this by forcing classloading with a
    ```new SpockApprovals()```
before I call verify, but I'm hoping we can figure out a better approach. Any thoughts?

**Comment by rzabini** [comment]
I think you are right, it seems a classloader issue. 
I am able to reproduce the error, but only when calling a single test.
At first sight, it may be solved by adding an explicit _verify_ method to class _SpockApprovals_:

```java
static void verify(obj){
         Approvals.verify(obj)
}
```

I will look into this.

**Comment by rzabini** [comment]
I managed to define a failing test, and then fixed it by adding the explicit method.
New version is 1.0.1, @dpost would you please verify if it works for you?

**Comment by dpost** [comment]
@rzabini I confirmed that the verify method does work as expected, but I also found that the verifyAsJson(obj) method throws the same exception as we saw previously with verify(obj)

**Comment by rzabini** [comment]
Yes, there is a general problem on not overridden methods, I opened issue #4
